resources:
  - common/configmap-azure-servicebus.yaml
  - common/secret-azure-servicebus.yaml
  - user
  - games
  - payments

labels:
  - pairs:
      app.kubernetes.io/part-of: cloudgames

# Allow cross-namespace app definitions via overlays
namespace: default
