# Patch to set environment variables for local k3d cluster
# - ASPNETCORE_ENVIRONMENT=Development: allows the application to use Connection String authentication instead of MSI
# - MESSAGE_BROKER_TYPE=AzureServiceBus: tells the application to use Azure Service Bus instead of RabbitMQ
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  template:
    spec:
      containers:
        - name: user-api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: MESSAGE_BROKER_TYPE
              value: "AzureServiceBus"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-api
spec:
  template:
    spec:
      containers:
        - name: games-api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: MESSAGE_BROKER_TYPE
              value: "AzureServiceBus"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
spec:
  template:
    spec:
      containers:
        - name: payments-api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: MESSAGE_BROKER_TYPE
              value: "AzureServiceBus"

