apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-app
  namespace: argocd
spec:
  project: payments
  source:
    repoURL: "https://github.com/rdpresser/tc-cloudgames-solution.git"
    targetRevision: feature/phase_04
    path: "infrastructure/kubernetes/overlays/dev"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudgames-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
