apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudgames-dev
  namespace: argocd
  labels:
    environment: dev
spec:
  project: cloudgames
  source:
    repoURL: "https://github.com/rdpresser/tc-cloudgames-solution.git"
    targetRevision: feature/phase_04
    path: "infrastructure/kubernetes/overlays/dev"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudgames-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Ignore differences in image tags - allow CI/CD to update them
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
