apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater-controller
  namespace: argocd-image-updater
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      containers:
      - name: argocd-image-updater-controller
        env:
        - name: ACR_NAME
          value: "tccloudgamesdevcr8nacr.azurecr.io"
        - name: AZURE_TENANT_ID
          value: "084169c0-a779-43c3-970c-487a71a93f88"
        volumeMounts:
        - name: auth
          mountPath: /app/auth
          readOnly: true
      volumes:
      - name: auth
        configMap:
          name: argocd-image-updater-auth
          defaultMode: 0755
