apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-api
  labels:
    app.kubernetes.io/name: user-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Add header with original path prefix for app to use (for PathBase/Swagger)
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-Prefix: /user";
spec:
  ingressClassName: nginx
  rules:
    - host: cloudgames.local
      http:
        paths:
          - path: /user(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-api
                port:
                  number: 8080