apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-api
  labels:
    app.kubernetes.io/name: games-api
    app.kubernetes.io/component: games
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: games-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: games-api
        app.kubernetes.io/component: games
    spec:
      containers:
        - name: games-api
          image: localhost:5000/games-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: AZURE_SERVICEBUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-servicebus-secret
                  key: AZURE_SERVICEBUS_CONNECTION_STRING
            - name: GAMES_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: azure-servicebus-config
                  key: gamesQueue
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
