apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: games-api
  labels:
    app.kubernetes.io/name: games-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-Prefix: /games";
spec:
  ingressClassName: nginx
  rules:
    - host: cloudgames.local
      http:
        paths:
          - path: /games(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: games-api
                port:
                  number: 8080