apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: games-api
  labels:
    app.kubernetes.io/name: games-api
spec:
  ingressClassName: nginx
  rules:
    - host: cloudgames.local
      http:
        paths:
          - path: /games
            pathType: Prefix
            backend:
              service:
                name: games-api
                port:
                  number: 8080