apiVersion: v1
kind: Service
metadata:
  name: games-api
  labels:
    app.kubernetes.io/name: games-api
  annotations:
    # ArgoCD service link - displayed in UI under Services tab
    service.argocd.argoproj.io/url: 'http://cloudgames.local/games'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: games-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http