apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payments-api
  labels:
    app.kubernetes.io/name: payments-api
spec:
  ingressClassName: nginx
  rules:
    - host: cloudgames.local
      http:
        paths:
          - path: /payments
            pathType: Prefix
            backend:
              service:
                name: payments-api
                port:
                  number: 8080