resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - external-secret.yaml
  - pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/component: payments
