apiVersion: v1
kind: Service
metadata:
  name: payments-api
  labels:
    app.kubernetes.io/name: payments-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payments-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http